# Generated by Django 3.0.3 on 2020-04-13 08:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Возрастной рейтинг')),
            ],
            options={
                'verbose_name': 'Возрастной рейтинг',
                'verbose_name_plural': 'Возрастные рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название формата')),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Форматы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата выхода')),
                ('duration', models.TimeField(verbose_name='Длительность')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('budget', models.PositiveIntegerField(default=0, help_text='Указать сумму в долларах', verbose_name='Бюджет')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='siteCin/', verbose_name='Постер')),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('countrys', models.ManyToManyField(to='siteCin.Country', verbose_name='Страны')),
                ('formats', models.ManyToManyField(to='siteCin.Format', verbose_name='Форматы')),
                ('genres', models.ManyToManyField(to='siteCin.Genre', verbose_name='Жанры')),
                ('restriction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteCin.AgeRating', verbose_name='Возрастной рейтинг')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='PlaceAndRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField(default=0, verbose_name='Ряд')),
                ('place', models.PositiveSmallIntegerField(default=0, verbose_name='Место')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteCin.Hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Место и ряд',
                'verbose_name_plural': 'Места и ряды',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('date_birth', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('gender', models.CharField(max_length=10, verbose_name='Пол')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('wishes', models.TextField(max_length=5000, verbose_name='Пожелания')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('cost', models.PositiveSmallIntegerField(default=0, help_text='Указать сумму в рублях', verbose_name='Стоимость')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteCin.Hall', verbose_name='Зал')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteCin.Movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sale', models.DateField(default=datetime.date.today, verbose_name='Дата продажи')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='siteCin.PlaceAndRow', verbose_name='Место и ряд')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='siteCin.Session', verbose_name='Сеанс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='siteCin.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteCin.Movie', verbose_name='Фильм')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteCin.Reviews', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='FormatHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteCin.Format', verbose_name='Формат')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteCin.Hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Формат_Зал',
                'verbose_name_plural': 'Форматы_Залы',
                'ordering': ('hall', 'formats'),
            },
        ),
    ]
