# Generated by Django 3.0.3 on 2020-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteCin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
            },
        ),
        migrations.AlterModelOptions(
            name='agerating',
            options={'ordering': ('name',), 'verbose_name': 'Возрастной рейтинг', 'verbose_name_plural': 'Возрастные рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('country',), 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'ordering': ('name',), 'verbose_name': 'Формат', 'verbose_name_plural': 'Форматы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='images/', verbose_name='Постер'),
        ),
    ]
