# Generated by Django 3.0.3 on 2020-06-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteCin', '0003_movie_actors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formathall',
            options={'ordering': ('hall',), 'verbose_name': 'Формат_Зал', 'verbose_name_plural': 'Форматы_Залы'},
        ),
        migrations.RemoveField(
            model_name='formathall',
            name='formats',
        ),
        migrations.AddField(
            model_name='formathall',
            name='formats',
            field=models.ManyToManyField(to='siteCin.Format', verbose_name='Форматы'),
        ),
    ]
