# Generated by Django 3.0.3 on 2020-06-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteCin', '0006_auto_20200629_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='movie',
        ),
    ]
