# Generated by Django 3.0.3 on 2020-06-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteCin', '0008_remove_reviews_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
    ]
