# Generated by Django 3.0.3 on 2020-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteCin', '0010_auto_20200630_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
