# Generated by Django 3.0.3 on 2020-06-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteCin', '0011_auto_20200630_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='siteCin.Movie', verbose_name='фильм'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='siteCin.Reviews', verbose_name='Родитель'),
        ),
    ]
