# Generated by Django 3.1.7 on 2021-02-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteCin', '0013_movie_poster_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('name',), 'verbose_name': 'Актеры', 'verbose_name_plural': 'Актеры'},
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя'),
        ),
    ]
